//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARWNI2S.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARWNI2S.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The argument may not be less than zero..
        /// </summary>
        internal static string Collections_ArgMustNotBeNegative {
            get {
                return ResourceManager.GetString("Collections_ArgMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The array is too small to hold all of the items..
        /// </summary>
        internal static string Collections_ArrayTooSmall {
            get {
                return ResourceManager.GetString("Collections_ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comparand is not of the correct type..
        /// </summary>
        internal static string Collections_BadComparandType {
            get {
                return ResourceManager.GetString("Collections_BadComparandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Collections_BadComparandType1 {
            get {
                return ResourceManager.GetString("Collections_BadComparandType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The \&quot;{0}\&quot; collection is read-only and cannot be modified..
        /// </summary>
        internal static string Collections_CannotModifyCollection {
            get {
                return ResourceManager.GetString("Collections_CannotModifyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The capacity may not be less than Count..
        /// </summary>
        internal static string Collections_CapacityLessThanCount {
            get {
                return ResourceManager.GetString("Collections_CapacityLessThanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collection was modified during an enumeration..
        /// </summary>
        internal static string Collections_ChangeDuringEnumeration {
            get {
                return ResourceManager.GetString("Collections_ChangeDuringEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Collections_ChangeDuringEnumeration1 {
            get {
                return ResourceManager.GetString("Collections_ChangeDuringEnumeration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The collection is empty..
        /// </summary>
        internal static string Collections_CollectionIsEmpty {
            get {
                return ResourceManager.GetString("Collections_CollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The collection may not be read only..
        /// </summary>
        internal static string Collections_CollectionIsReadOnly {
            get {
                return ResourceManager.GetString("Collections_CollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The collection has become too large..
        /// </summary>
        internal static string Collections_CollectionTooLarge {
            get {
                return ResourceManager.GetString("Collections_CollectionTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Compare method is not supported on an identity comparer..
        /// </summary>
        internal static string Collections_IdentityComparerNoCompare {
            get {
                return ResourceManager.GetString("Collections_IdentityComparerNoCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The two collections cannot be combined because they use different comparison operations..
        /// </summary>
        internal static string Collections_InconsistentComparisons {
            get {
                return ResourceManager.GetString("Collections_InconsistentComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The load factor must be between 0.25 and 0.95..
        /// </summary>
        internal static string Collections_InvalidLoadFactor {
            get {
                return ResourceManager.GetString("Collections_InvalidLoadFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The key was already present in the dictionary..
        /// </summary>
        internal static string Collections_KeyAlreadyPresent {
            get {
                return ResourceManager.GetString("Collections_KeyAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The key was not found in the collection..
        /// </summary>
        internal static string Collections_KeyNotFound {
            get {
                return ResourceManager.GetString("Collections_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The list may not be read only..
        /// </summary>
        internal static string Collections_ListIsReadOnly {
            get {
                return ResourceManager.GetString("Collections_ListIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The get accessor of the indexer must be overridden..
        /// </summary>
        internal static string Collections_MustOverrideIndexerGet {
            get {
                return ResourceManager.GetString("Collections_MustOverrideIndexerGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The set accessor of the indexer must be overridden..
        /// </summary>
        internal static string Collections_MustOverrideIndexerSet {
            get {
                return ResourceManager.GetString("Collections_MustOverrideIndexerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This method must be overridden or re-implemented in the derived class..
        /// </summary>
        internal static string Collections_MustOverrideOrReimplement {
            get {
                return ResourceManager.GetString("Collections_MustOverrideOrReimplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The argument is outside the range of this View..
        /// </summary>
        internal static string Collections_OutOfViewRange {
            get {
                return ResourceManager.GetString("Collections_OutOfViewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset is not supported on this enumerator..
        /// </summary>
        internal static string Collections_ResetNotSupported {
            get {
                return ResourceManager.GetString("Collections_ResetNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Collections_ResetNotSupported1 {
            get {
                return ResourceManager.GetString("Collections_ResetNotSupported1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type \&quot;{0}\&quot; does not implement ICloneable..
        /// </summary>
        internal static string Collections_TypeNotCloneable {
            get {
                return ResourceManager.GetString("Collections_TypeNotCloneable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;{0}&quot; does not implement IComparable&lt;{0}&gt; or IComparable..
        /// </summary>
        internal static string Collections_UncomparableType {
            get {
                return ResourceManager.GetString("Collections_UncomparableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value \&quot;{0}\&quot; isn&apos;t of type \&quot;{1}\&quot; and can&apos;t be used in this generic collection..
        /// </summary>
        internal static string Collections_WrongType {
            get {
                return ResourceManager.GetString("Collections_WrongType", resourceCulture);
            }
        }
    }
}
