//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI2S.Node.Analyzers {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NI2S.Node.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The member &quot;{0}&quot; is marked as {1} and therefore cannot be serialized.
        /// </summary>
        internal static string AbstractOrStaticMembersCannotBeSerializedMessageFormat {
            get {
                return ResourceManager.GetString("AbstractOrStaticMembersCannotBeSerializedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Members which are static or abstract cannot be serialized.
        /// </summary>
        internal static string AbstractOrStaticMembersCannotBeSerializedTitle {
            get {
                return ResourceManager.GetString("AbstractOrStaticMembersCannotBeSerializedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add the [GenerateSerializer] attribute to serializable types in your application.
        /// </summary>
        internal static string AddGenerateSerializerAttributeDescription {
            get {
                return ResourceManager.GetString("AddGenerateSerializerAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type &quot;{0}&quot; has the [Serializable] attribute but not the [GenerateSerializer] attribute.
        /// </summary>
        internal static string AddGenerateSerializerAttributeMessageFormat {
            get {
                return ResourceManager.GetString("AddGenerateSerializerAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add the [GenerateSerializer] attribute.
        /// </summary>
        internal static string AddGenerateSerializerAttributesTitle {
            get {
                return ResourceManager.GetString("AddGenerateSerializerAttributesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add attributes to properties and fields to direct serializer generation.
        /// </summary>
        internal static string AddSerializationAttributesDescription {
            get {
                return ResourceManager.GetString("AddSerializationAttributesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add missing serialization attributes.
        /// </summary>
        internal static string AddSerializationAttributesMessageFormat {
            get {
                return ResourceManager.GetString("AddSerializationAttributesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add missing serialization attributes.
        /// </summary>
        internal static string AddSerializationAttributesTitle {
            get {
                return ResourceManager.GetString("AddSerializationAttributesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A single type is not allowed to have multiple constructors annotated with the [OrleansConstructor] attribute.
        /// </summary>
        internal static string AtMostOneOrleansConstructorMessageFormat {
            get {
                return ResourceManager.GetString("AtMostOneOrleansConstructorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At most one constructor can be annotated with the [OrleansConstructor] attribute.
        /// </summary>
        internal static string AtMostOneOrleansConstructorTitle {
            get {
                return ResourceManager.GetString("AtMostOneOrleansConstructorTitle", resourceCulture);
            }
        }
    }
}
